version: "3.7"

services:
  qg-subscription-mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3008"]
    ports:
      - 31008:3008
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3008/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon-mocks.json:/data:ro

